DROP DATABASE IF EXISTS neight;
CREATE DATABASE neight;

CREATE USER neight WITH ENCRYPTED PASSWORD '8qLKJbXuA9bwkNMreWb8' CREATEDB;
GRANT ALL PRIVILEGES ON DATABASE neight TO neight;

\c neight;
CREATE SCHEMA neight AUTHORIZATION neight;